version: 2.1

orbs:
  dwave: dwave/orb-examples@2

workflows:
  version: 2.1
  tests:
    jobs:
      - dwave/test-linux
      - dwave/test-osx
      - dwave/test-win

  weekly:
    triggers:
      - schedule:
          cron: "0 4 * * 6"
          filters:
            branches:
              only:
                - master
                - main
    jobs:
      - dwave/test-linux:
          integration-tests: "canary"
      - dwave/test-osx:
          integration-tests: "skip"
      - dwave/test-win:
          integration-tests: "skip"
